{% set name = "gitea" %}
{% set version = "1.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/go-gitea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 9fb3a68d906f6333a7c2207e93dcb4249b1b9f3617da1961b28a9d6ac76cd3de

build:
  number: 0

requirements:
  build:
    - {{ compiler('cgo') }} 1.22
    - {{ compiler('c') }}
    - file  # [not win]
    - go-licenses >=1.6.0
    - make
    - nodejs >=20
    # Makefile uses some unix bash commands
    - m2-filesystem  # [win]
    - m2-bash  # [win]
    - m2-base  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
  run:
    - git

test:
  commands:
    - gitea --version
    - gitea --help

about:
  home: https://about.gitea.com
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Git with a cup of tea
  description: |
      The goal of this project is to make the easiest, fastest, and most
      painless way of setting up a self-hosted Git service.
  dev_url: https://github.com/go-gitea/gitea
  doc_url: https://docs.gitea.com

extra:
  recipe-maintainers:
    - manics
    - nehaljwani
