{% set name = "gitea" %}
{% set version = "1.21.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/go-gitea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: d6464552df69636bfe5883e54870fe31eec0e602954ab16b94d297f3913498a5

build:
  number: 0

requirements:
  build:
    - {{ compiler('cgo') }} 1.21
    - {{ compiler('c') }}
    - file  # [not win]
    - go-licenses >=1.6.0
    - make
    - nodejs >=20
    # Makefile uses some unix bash commands
    - m2-filesystem  # [win]
    - m2-bash  # [win]
    - m2-base  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
  run:
    - git

test:
  commands:
    - gitea --version
    - gitea --help

about:
  home: https://gitea.io
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Git with a cup of tea
  description: |
      The goal of this project is to make the easiest, fastest, and most
      painless way of setting up a self-hosted Git service.
  dev_url: https://github.com/go-gitea/gitea
  doc_url: https://docs.gitea.io

extra:
  recipe-maintainers:
    - manics
    - nehaljwani
