{% set name = "gitea" %}
{% set version = "1.22.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/go-gitea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: beeeac8712dabfbdcde8a2cd7eb2a4c23ac600ef82fc85fc4cced6d008b9aa52

build:
  number: 0
  # Can't currently build on Windows, but config is kept so we can try again in future
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cgo') }} 1.22
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - file  # [not win]
    - go-licenses >=1.6.0
    - make
    - nodejs >=20
    # Makefile uses some unix bash commands
    - m2-filesystem  # [win]
    - m2-bash  # [win]
    - m2-base  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
  run:
    - git

test:
  commands:
    - gitea --version
    - gitea --help

about:
  home: https://about.gitea.com
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Git with a cup of tea
  description: |
    The goal of this project is to make the easiest, fastest, and most
    painless way of setting up a self-hosted Git service.
  dev_url: https://github.com/go-gitea/gitea
  doc_url: https://docs.gitea.com

extra:
  recipe-maintainers:
    - manics
    - nehaljwani
    - techknowlogick
