{% set name = "gitea" %}
{% set version = "1.24.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/go-gitea/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a530458b1e80758d882d4ba9a2bab518a4747fcbcac1f6c951de72b398f442ce

build:
  number: 0
  # Can't currently build on Windows, but config is kept so we can try again in future
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cgo') }} 1.24
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - file  # [not win]
    # - go-licenses >=1.6.0
    # For unknown reasons we've started hitting
    # https://github.com/google/go-licenses/issues/128
    - go-licenses <1.1
    - make
    - nodejs >=20
    # Makefile uses some unix bash commands
    - m2-filesystem  # [win]
    - m2-bash  # [win]
    - m2-base  # [win]
    - m2-grep  # [win]
    - m2-sed  # [win]
  run:
    - git

test:
  commands:
    - gitea --version
    - gitea --help

about:
  home: https://about.gitea.com
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Git with a cup of tea
  description: |
    The goal of this project is to make the easiest, fastest, and most
    painless way of setting up a self-hosted Git service.
  dev_url: https://github.com/go-gitea/gitea
  doc_url: https://docs.gitea.com

extra:
  recipe-maintainers:
    - manics
    - nehaljwani
    - techknowlogick
