travis:
  secure:
    BINSTAR_TOKEN: V1CyWbURZ+ZiYLxPGjLx3eN+d0GH4tKRBBFLEzMnO72rebzZzUhJmyuoiT+6nHqxP3OvMbO2YUF35+kAR4N7iz5irDhrwKRAtTCN7Hvo54l1DOYk/gh2/Apb+0hu2GQRDVAOwXPJLuXB4h3OfojXiyuH7Y/v7jazU5Eu45Y0wnThoDBB/lKfJJsO20m6PjMiJf9pfQXqTHaRuYUL33lfPAcoSOOV6RYVlI3rTnrUrg2s22ZmhPMkihBSZ5audjLYGSXOwn2DFISbs4hqhtYvXGvUxm+9T2yEKVSxppXRN9W84CAQz6hmErMTCMJvF+5pIB19/Z83mf0InWUq++6arVYmj4GtJbRDptza5H4ickJpCbpq6MIASABBulk/S0fEYRfJqHHHENVXOG9Kli3y2+QIMBlHS5tDIPsHupwIhTodMx/N0NAl6QFCstp0d3OdQ0m2ih70zdzhFGZ9ZejHp3zuf5zLMZ/Hym3Gjscb88Qz3L42h7LuVJnzWdLl7qOiyjs+MZxTRoyHK4t5VNCT4YiTsfx6eU8p2CACIxwueZ9e9tK9sKUWjvU0rQJLt2+84VckIsEljzrgWEiZjgwvp13oeaG5QXPYM5uR3FNx20mqmBoEUHO6IgCJKd4WnJwGFxuvqbEHgBjyzY54y5N61Cseet6M4g3hhxMDmKEi3WI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
